name: ${project.artifactId}
authors: ${project.authors}
version: ${project.version}
main: ${project.main}
description: >
             Make protections
depend: [WorldGuard, WorldEdit]
commands:
    protect:
        description: "Make a protection"
        usage: "§cDo /prot help."
        aliases: [prot]
permissions:
    pgc.prot.admin:
        description: If you are allowed to create and remove protections
        